repos:
  - repo: local
    hooks:
      - id: black
        name: black
        types: [python]
        language: system
        entry: black .
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        types: [python]
        language: system
        entry: flake8 --config backend/.flake8 .
        